name = "TensorAutoregressions"
uuid = "363a7405-726f-4af3-8d92-de3cb59efcc2"
authors = ["Quint Wiersma <qnt.wrsm@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StateSpace = "d0afd82c-d9a7-4a5a-8bb8-d8f08074e575"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
